server:
  port: 8080

spring:
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
        
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: 
        driver-class-name: com.mysql.jdbc.Driver

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ddwangx.learnspringboot.pojo  # 注意：对应实体类的路径
