server:
  port: 8080

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.jdbc.Driver
  #redis配置，以下有默认配置的也可以使用默认配置
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    jedis: 
      pool:
        min-idle: 5
        max-active: 10
        max-wait: 2000
        max-idle: 10


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.ddwangx.learnspringboot.pojo  # 注意：对应实体类的路径
